<?php
// --- PDO Database Connection ---

// Include the central configuration file.
// This file is generated by install.php and contains all sensitive details.
require_once __DIR__ . '/config.php';

// Data Source Name (DSN)
$dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=" . DB_CHARSET;

// PDO options for the connection
$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION, // Throw exceptions on errors
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,       // Fetch associative arrays
    PDO::ATTR_EMULATE_PREPARES   => false,                  // Use native prepared statements
];

try {
    // Create a new PDO instance using constants from config.php
    $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
} catch (\PDOException $e) {
    // If connection fails, stop the script and show a user-friendly error.
    // In a real production environment, you might log this error and show a generic message.
    die("Database connection failed: " . $e->getMessage());
}

// The $pdo object is now ready to be used by any script that includes this file.
